### ISSUE TITLE
Blank vnc 

### ISSUE THREAD

**Issue by lawbyte** [noob-hackers/kalimux#20]
![Screenshot_20210718-101450](https://user-images.githubusercontent.com/35652825/126054477-149e3643-8433-4e36-aefe-c61318e05958.png)
![Screenshot_20210718-101617](https://user-images.githubusercontent.com/35652825/126054480-b4061ed9-f678-4d08-b48a-1012c603e1df.png)

**Comment by Ikikass** [comment]
I've got the same problem.

**Comment by whitedevil0420** [comment]
Where is error
Open vnc and boom

**Comment by Ikikass** [comment]
The solution is actually "apt update && apt upgrade" followed by "apt  install dbus-x11"
